# Generated by Django 2.1.7 on 2019-03-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='English',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=100)),
                ('m_director', models.CharField(max_length=100)),
                ('m_hero', models.CharField(max_length=100)),
                ('m_heroine', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hindi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=100)),
                ('m_director', models.CharField(max_length=100)),
                ('m_hero', models.CharField(max_length=100)),
                ('m_heroine', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Telugu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=100)),
                ('m_director', models.CharField(max_length=100)),
                ('m_hero', models.CharField(max_length=100)),
                ('m_heroine', models.CharField(max_length=100)),
            ],
        ),
    ]
