# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-15 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.IntegerField()),
                ('product_name', models.CharField(max_length=20)),
                ('product_cost', models.IntegerField()),
                ('product_class', models.CharField(max_length=20)),
                ('product_weight', models.IntegerField()),
            ],
        ),
    ]
